### ISSUE TITLE
can you share about pig mot dataset ? tks!

### ISSUE THREAD

**Issue by AprilWinds** [gorodion/PigTracking#1]

**Comment by gorodion** [comment]
Hey!
Of course
[Detection dataset](https://wi2.uni-hohenheim.de/fileadmin/einrichtungen/wi2/Publikationen/COMPAG_105391_Riekert_etal_2020.zip) and [detection training notebook](https://colab.research.google.com/drive/1d0fk_xiUQl5cwyDm3B858SQ0CIv526Tx?usp=sharing)
Also [Our segmentation markup](https://app.supervise.ly/h5un6l2bnaz1vj8a9qgms4-public/tasks/archives/2/3/dH/cIjh85tiWDcjezihiKHa9I8Mc0U3nAInxUEUwgS4ZjZrGxDFD0r2h7rBhnmcDT0OxmRgcOsaxxoMk0oQN1kg1vtEjWTRWIBvKBWAAZsK97ia4lTYyUQr12kCpN4R.tar) and [segmentation training notebook](https://colab.research.google.com/drive/1o_I_ycCc2BFeJU9Wn8m60gOxBNv9LNPT?usp=sharing)

**Comment by AprilWinds** [comment]
thanks
